# Generated by Django 2.1.1 on 2018-10-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0001_initial'),
        ('user', '0004_auto_20181022_1010'),
        ('tips', '0002_auto_20181022_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('approve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
                ('content_share_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.share')),
                ('content_tips_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.tips')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('content_share_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.share')),
                ('content_tips_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.tips')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
            ],
        ),
    ]
