# Generated by Django 2.1.1 on 2018-10-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teamstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(unique=True)),
                ('status_name', models.CharField(max_length=20)),
                ('spare1', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
