# Generated by Django 2.1.1 on 2018-10-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181022_1010'),
        ('travelteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, unique=True)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('launch_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelteam.teamstatus', to_field='status_id')),
            ],
        ),
    ]
