# Generated by Django 2.1.1 on 2018-10-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelteam', '0004_city_teamroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='attractionbaseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=200, unique=True)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelteam.city', to_field='city_name')),
            ],
        ),
        migrations.CreateModel(
            name='attractioninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_intro', models.CharField(max_length=10000)),
                ('attraction_img', models.CharField(max_length=10000)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('attraction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelteam.attractionbaseinfo', to_field='attraction_name')),
            ],
        ),
    ]
