# Generated by Django 2.1.1 on 2018-10-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181022_1010'),
        ('travelteam', '0005_attractionbaseinfo_attractioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='followuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('real_name', models.CharField(max_length=100, null=True)),
                ('license_num', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=40, null=True)),
                ('weichat', models.CharField(max_length=255, null=True)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelteam.team', to_field='team_name')),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
            ],
        ),
    ]
