# Generated by Django 2.1.1 on 2018-10-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelteam', '0006_followuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travelteam.teamstatus', to_field='status_id'),
        ),
    ]
