# Generated by Django 2.1.1 on 2018-10-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181022_1010'),
        ('question', '0002_auto_20181022_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('answser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', to_field='question_id')),
            ],
        ),
    ]
