# Generated by Django 2.1.1 on 2018-10-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelteam', '0006_followuser'),
        ('user', '0004_auto_20181022_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_introduce', models.CharField(max_length=2000, null=True)),
                ('image', models.CharField(max_length=1000, null=True)),
                ('feeling', models.CharField(max_length=10000, null=True)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('launch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='name')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelteam.team', to_field='team_name')),
            ],
        ),
    ]
