# Generated by Django 2.1.1 on 2018-10-22 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('spare1', models.CharField(max_length=255, null=True)),
                ('spare2', models.CharField(max_length=255, null=True)),
                ('permission', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.userpermission', to_field='permission_id')),
            ],
        ),
    ]
